image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Installing PostgreSQL..."
      sudo apt-get update
      sudo apt-get install -y postgresql postgresql-contrib
      sudo service postgresql start
      echo "Creating database..."
      sudo -u postgres psql -c "CREATE USER gitpod WITH PASSWORD '214365';"
      sudo -u postgres psql -c "CREATE DATABASE mydatabase OWNER gitpod;"
      echo "PostgreSQL setup complete."
    command: |
      echo "Starting application..."
      # Start your application here, e.g., `npm start` or `python app.py`

ports:
  - port: 5432
    onOpen: ignore

env:
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_USER: gitpod
  DATABASE_PASSWORD: 214365
  DATABASE_NAME: mydatabase