image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Setting up PostgreSQL..."
      export PGPASSWORD=mysecretpassword
      psql -h localhost -U gitpod -d postgres -c "CREATE DATABASE mydatabase;"
      echo "PostgreSQL setup complete."
    command: |
      echo "Starting application..."
      # Start your application here, e.g., `npm start` or `python app.py`

ports:
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - bradlc.vscode-tailwindcss